---
title: "chemo-dd"
subtitle: "Supplementary plots"
output: 
  html_notebook:
    toc: true
    toc_depth: 4
author: "James Orr"
---

This notebook uses the processed data from `1-data-prep.Rmd` for creating supplementary plots. 


### Set up environment 

Load packages and clear environment 

```{r}
#### Required packages
library(tidyverse) 
library(cowplot)

#### Clear  environment 
rm(list = ls())   
```

Load data

```{r}
all_samples <- read.csv("data/processed/all_samples.csv")
equilibrium_samples <- read.csv("data/processed/equilibrium_samples.csv")
chibio <- read.csv("data/processed/chibio.csv")

# "final" datasets
chemo_dd_eqs_av <- read.csv("data/processed/equilibrium_samples_av.csv")
chemo_dd_eqs_last <- read.csv("data/processed/equilibrium_samples_last.csv")
chemo_dd_eqs_first <- read.csv("data/processed/equilibrium_samples_first.csv")
chemo_dd_eqs_day1 <- read.csv("data/processed/equilibrium_samples_day1.csv")
chemo_dd_eqs_day2 <- read.csv("data/processed/equilibrium_samples_day2.csv")
chemo_dd_eqs_day3 <- read.csv("data/processed/equilibrium_samples_day3.csv")
chemo_dd_eqs_day4 <- read.csv("data/processed/equilibrium_samples_day4.csv")
```

### Densities per day for each experiment

```{r}
ggplot(all_samples, aes(y = cfu_ul, x = dilution_rate, color = day)) +
  geom_point() + 
  labs(y = "CFU/μL", x = "Dilution rate (ml/hour/ml)", color = "day") +
  scale_color_gradient(low = "#3BDCB4", high = "#185266", name = "Day") + 
  theme_light() +
  facet_wrap(~ experiment_replicate, scales = "free_y")
```

```{r}
ggplot(all_samples, aes(y = od_blanked, x = dilution_rate, color = day)) +
  geom_point() + 
  labs(y = "OD", x = "Dilution rate (ml/hour/ml)", color = "day") +
  scale_color_gradient(low = "#3BDCB4", high = "#185266", name = "Day") + 
  theme_light() +
  facet_wrap(~ experiment_replicate, scales = "free_y")
```

Cutoff between low, intermediate, and high dilution rates

Only include up to and including day 4

```{r, fig.height=5, fig.width=10}

ggplot(subset(all_samples, all_samples$day < 5), 
       aes(y = od_blanked, x = dilution_rate, 
           color = day, shape = experiment_replicate)) +
  
  # Add shaded regions
  geom_rect(aes(xmin = -Inf, xmax = 0.1, ymin = -Inf, ymax = Inf), 
            fill = "gray99", inherit.aes = FALSE) + 
  geom_rect(aes(xmin = 0.1, xmax = 0.75, ymin = -Inf, ymax = Inf), 
            fill = "gray95", inherit.aes = FALSE) + 
  geom_rect(aes(xmin = 0.75, xmax = Inf, ymin = -Inf, ymax = Inf), 
            fill = "gray90", inherit.aes = FALSE) +   
  
  geom_point(size = 4, alpha = 1) + 

  geom_vline(xintercept = c(0.1, 0.75), linetype = "dashed", color = "gray50") + # Vertical lines

  geom_line(aes(group = dilution_rate), linetype = "solid", 
            color = "black", size = 1.5, alpha = 0.3) + 

  scale_color_gradient(low = "#3BDCB4", high = "#185266", name = "Day") + 
  
  scale_shape_manual(values = c(15:19), name = "Replicate") +

  labs(y = "OD", x = "Dilution rate (ml/hour/ml)") + 
    
  theme_light() +
  
  theme(
    axis.title.x = element_text(size = 16),  # Increase x-axis label size
    axis.title.y = element_text(size = 16),  # Increase y-axis label size
    axis.text.x = element_text(size = 14),   # Increase x-axis tick text size
    axis.text.y = element_text(size = 14),   # Increase y-axis tick text size
    legend.title = element_text(size = 14),  # Increase legend title text size
    legend.text = element_text(size = 12)    # Increase legend text size
  )


```

### Equilibrium densities by dilution rate

#### CFUs 


```{r, fig.height=5, fig.width=15}
p1 <- ggplot(equilibrium_samples, aes(y = cfu_ul, 
                                      x = dilution_rate, 
                                      shape = experiment_replicate)) +
  geom_point(size = 2) + 
  labs(y = "CFU/μL", x = "Dilution rate (ml/hour/ml)",
       title = "chemo_dd_eqs") +
  scale_shape_manual(values = c(15:19), name = "Replicate") +
  theme_minimal()


p2 <- ggplot(chemo_dd_eqs_av, aes(y = cfu_ul, 
                                      x = dilution_rate, 
                                      shape = experiment_replicate)) +
  geom_point(size = 2) + 
  labs(y = "CFU/μL", x = "Dilution rate (ml/hour/ml)",
       title = "chemo_dd_eqs_av") +
  scale_shape_manual(values = c(15:19), name = "Replicate") +
  theme_minimal()



p3 <- ggplot(chemo_dd_eqs_first, aes(y = cfu_ul, 
                                      x = dilution_rate, 
                                      shape = experiment_replicate)) +
  geom_point(size = 2) + 
  labs(y = "CFU/μL", x = "Dilution rate (ml/hour/ml)",
       title = "chemo_dd_eqs_first") +
  scale_shape_manual(values = c(15:19), name = "Replicate") +
  theme_minimal()



p4 <- ggplot(chemo_dd_eqs_last, aes(y = cfu_ul, 
                                      x = dilution_rate, 
                                      shape = experiment_replicate)) +
  geom_point(size = 2) + 
  labs(y = "CFU/μL", x = "Dilution rate (ml/hour/ml)",
       title = "chemo_dd_eqs_last") +
  scale_shape_manual(values = c(15:19), name = "Replicate") +
  theme_minimal()



p5 <- ggplot(chemo_dd_eqs_day1, aes(y = cfu_ul, 
                                      x = dilution_rate, 
                                      shape = experiment_replicate)) +
  geom_point(size = 2) + 
  labs(y = "CFU/μL", x = "Dilution rate (ml/hour/ml)",
       title = "chemo_dd_eqs_day1") +
  scale_shape_manual(values = c(15:19), name = "Replicate") +
  theme_minimal()

p6 <- ggplot(chemo_dd_eqs_day2, aes(y = cfu_ul, 
                                      x = dilution_rate, 
                                      shape = experiment_replicate)) +
  geom_point(size = 2) + 
  labs(y = "CFU/μL", x = "Dilution rate (ml/hour/ml)",
       title = "chemo_dd_eqs_day2") +
  scale_shape_manual(values = c(15:19), name = "Replicate") +
  theme_minimal()

p7 <- ggplot(chemo_dd_eqs_day3, aes(y = cfu_ul, 
                                      x = dilution_rate, 
                                      shape = experiment_replicate)) +
  geom_point(size = 2) + 
  labs(y = "CFU/μL", x = "Dilution rate (ml/hour/ml)",
       title = "chemo_dd_eqs_day3") +
  scale_shape_manual(values = c(15:19), name = "Replicate") +
  theme_minimal()

p8 <- ggplot(chemo_dd_eqs_day4, aes(y = cfu_ul, 
                                      x = dilution_rate, 
                                      shape = experiment_replicate)) +
  geom_point(size = 2) + 
  labs(y = "CFU/μL", x = "Dilution rate (ml/hour/ml)",
       title = "chemo_dd_eqs_day4") +
  scale_shape_manual(values = c(15:19), name = "Replicate") +
  theme_minimal()


plot_grid(p1, p2, p3, p4,
          p5, p6, p7, p8,
          nrow = 2)
```

#### OD

```{r, fig.height=5, fig.width=15}
p1 <- ggplot(equilibrium_samples, aes(y = od_blanked, 
                                      x = dilution_rate, 
                                      shape = experiment_replicate)) +
  geom_point(size = 2) + 
  labs(y = "OD", x = "Dilution rate (ml/hour/ml)",
       title = "chemo_dd_eqs") +
  scale_shape_manual(values = c(15:19), name = "Replicate") +
  theme_minimal()


p2 <- ggplot(chemo_dd_eqs_av, aes(y = od_blanked, 
                                      x = dilution_rate, 
                                      shape = experiment_replicate)) +
  geom_point(size = 2) + 
  labs(y = "OD", x = "Dilution rate (ml/hour/ml)",
       title = "chemo_dd_eqs_av") +
  scale_shape_manual(values = c(15:19), name = "Replicate") +
  theme_minimal()



p3 <- ggplot(chemo_dd_eqs_first, aes(y = od_blanked, 
                                      x = dilution_rate, 
                                      shape = experiment_replicate)) +
  geom_point(size = 2) + 
  labs(y = "OD", x = "Dilution rate (ml/hour/ml)",
       title = "chemo_dd_eqs_first") +
  scale_shape_manual(values = c(15:19), name = "Replicate") +
  theme_minimal()



p4 <- ggplot(chemo_dd_eqs_last, aes(y = od_blanked, 
                                      x = dilution_rate, 
                                      shape = experiment_replicate)) +
  geom_point(size = 2) + 
  labs(y = "OD", x = "Dilution rate (ml/hour/ml)",
       title = "chemo_dd_eqs_last") +
  scale_shape_manual(values = c(15:19), name = "Replicate") +
  theme_minimal()



p5 <- ggplot(chemo_dd_eqs_day1, aes(y = od_blanked, 
                                      x = dilution_rate, 
                                      shape = experiment_replicate)) +
  geom_point(size = 2) + 
  labs(y = "OD", x = "Dilution rate (ml/hour/ml)",
       title = "chemo_dd_eqs_day1") +
  scale_shape_manual(values = c(15:19), name = "Replicate") +
  theme_minimal()

p6 <- ggplot(chemo_dd_eqs_day2, aes(y = od_blanked, 
                                      x = dilution_rate, 
                                      shape = experiment_replicate)) +
  geom_point(size = 2) + 
  labs(y = "OD", x = "Dilution rate (ml/hour/ml)",
       title = "chemo_dd_eqs_day2") +
  scale_shape_manual(values = c(15:19), name = "Replicate") +
  theme_minimal()

p7 <- ggplot(chemo_dd_eqs_day3, aes(y = od_blanked, 
                                      x = dilution_rate, 
                                      shape = experiment_replicate)) +
  geom_point(size = 2) + 
  labs(y = "OD", x = "Dilution rate (ml/hour/ml)",
       title = "chemo_dd_eqs_day3") +
  scale_shape_manual(values = c(15:19), name = "Replicate") +
  theme_minimal()

p8 <- ggplot(chemo_dd_eqs_day4, aes(y = od_blanked, 
                                      x = dilution_rate, 
                                      shape = experiment_replicate)) +
  geom_point(size = 2) + 
  labs(y = "OD", x = "Dilution rate (ml/hour/ml)",
       title = "chemo_dd_eqs_day4") +
  scale_shape_manual(values = c(15:19), name = "Replicate") +
  theme_minimal()


plot_grid(p1, p2, p3, p4,
          p5, p6, p7, p8,
          nrow = 2)

rm(p1, p2, p3, p4, p5, p6, p7, p8)
```


### Chibio OD timeseries


```{r, fig.height=6, fig.width=10}
  
chibio_plot <- chibio %>%
  # remove control
  filter(!(ID %in% c("M2"))) %>%
  
  # remove M3 after day 2 (pump failed)
  filter(!(ID %in% c("M3") & hours > 48)) %>%
  
  # remove all points after day 4 (system stopped) 
  filter(!(hours > 96))
  

ggplot(chibio_plot, aes(x = hours, y = od_measured, 
                   group = ID, color = dilution_rate)) +
  
  # Each observation 
  geom_point(alpha = 0.1, size = 0.5) +
  
  # Smoothed lines for each ID
  geom_smooth(aes(group = ID), method = "loess", 
              se = FALSE, size = 1.2, span = 0.15) +
  
  # Set a continuous color gradient 
  scale_color_gradient(low = "#3BDCB4", high = "#185266") +
  
  # Add vertical lines for sampling moments
  geom_vline(xintercept = c(24, 48, 72, 96),
             linetype = "dashed", color = "grey40", size = 0.5) +
  
  # Add labels and title
  labs(x = "Hours", y = "OD", color = "Dilution Rate") +
  
  theme_minimal() +
  theme(legend.position = "right")
```


